; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = t-camera-sim
default_envs = espcam 
src_dir = src

[env]
platform = espressif32@6.3.0
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = 
	default
	esp32_exception_decoder

[esp32dev_base]
board = esp32dev
build_flags = 
	${env.build_flags}
lib_deps = 
	${env.lib_deps}

[esp32doit-devkit-v1]
board = esp32doit-devkit-v1
build_flags = 
	${env.build_flags}
lib_deps = 
	${env.lib_deps}

[esp32s3_base]
board = esp32s3box
build_flags = 
	${env.build_flags}
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0
lib_deps = 
	${env.lib_deps}

[env:espcam]
; extends = esp32dev_base
extends = esp32doit-devkit-v1
; board = esp32cam
; upload_speed = 115200
; upload_protocol = esptool
upload_resetmethod = no_reset
build_src_filter =
	+<**/sza_espcam.cpp>
	-<**/sza_simcam.cpp>
build_flags = 
	; ${esp32dev_base.build_flags}
	${esp32doit-devkit-v1.build_flags}
lib_deps = 
	; ${esp32dev_base.lib_deps}
	${esp32doit-devkit-v1.lib_deps}
	bogde/HX711@^0.7.5

[env:t-camera-sim]
extends = esp32s3_base
; board_build.arduino.memory_type = qio_opi
; board_build.psram_type = opi
build_src_filter =
	+<**/sza_simcam.cpp>
  	-<**/sza_espcam.cpp>
build_flags = 
	${esp32s3_base.build_flags}
	-DBOARD_HAS_PSRAM
	-DCAMERA_MODEL_TTGO_T_CAM_SIM
lib_deps = 
	${esp32s3_base.lib_deps}
	bogde/HX711@^0.7.5
lib_ignore = 
	TFT_eSPI
board_build.partitions = default_16MB.csv
